# Generated by Django 3.1 on 2022-05-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220521_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=30, verbose_name='題名')),
                ('author', models.CharField(max_length=30, verbose_name='著者')),
                ('price', models.IntegerField(verbose_name='価格')),
            ],
        ),
    ]
