# Generated by Django 3.1 on 2022-05-22 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220521_2328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
